### ISSUE TITLE
How to make it usable directly in the browser?

### ISSUE THREAD

**Issue by andrevmatos** [bersling/typescript-library-starter#2]
Checked using `-m umd`, but it only works with RequireJS or alikes. How to make my simple library available to be included in a browser environment through a `<script>` tag?

**Comment by bersling** [comment]
It depends a bit. In the simplest case, if you just have, let's say `dist/simple.js`, you can simply include it with a script tag, e.g. `src="../node_modules/yourlib/simple.js"`. In other cases you'll need a module loader like SytemJS, see e.g. https://www.bersling.com/2016/08/24/es6-modules-and-typescript/ . Or if you have other node modules, you can use browserify: http://browserify.org/ .
