### ISSUE TITLE
Question: Is using namespaces a best practise?

### ISSUE THREAD

**Issue by bitflower** [bersling/typescript-library-starter#3]
Hi,

first of all thanks for this great starter. Worked out of the box after trying some other tuts and starters... 

I have one question though about the folder structure / namespacing of a more complex library.

I'm building a library that will have folder like "controllers", "models", .etc. Inside of these I will have files:
root
-- src
----- index.ts
----- controllers
-------- controller1.ts

With your approach I would have to namespace these files inside each file because in index.ts they are "thrown together for export". Is this correct?

Now, when using my library in a node app I would love to be able to only import a sub module like for example 
```javascript
import { Controller1 } from 'my-lib/controllers/controller1';
```

Is this the way to go then by using namespaces? Somehow namespaces for "wrong" to me...

Thanks you for a hint

**Comment by bersling** [comment]
Hi, I haven't found an official statement about this, but namespaces for sure aren't the industry standard. The community seems to converge more towards classes

**Comment by bitflower** [comment]
Hey, thanks for getting back. Instead of using namespaces I now create a file for each folder called index.js and export form there what the "namespace" is supposed to offer.
